### ISSUE TITLE
support non-corda CA tree

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-discovery#42]
- [x] setup scripts for keys (also in nuts-network-setup)
- [x] configuration for extra keys
- [x] endpoints and logic (similar to how Corda handles it)
- [x] spec and docs on endpoints

**Comment by woutslakhorst** [comment]
see #43

**Comment by woutslakhorst** [comment]
see #45

**Comment by woutslakhorst** [comment]
ClosedBy #49
